CREATE TABLE table_products(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK ( name != '' ),
    price NUMERIC(10,2) NOT NULL CHECK ( price >= 0.0 )
);

INSERT INTO table_products (name, price) 
VALUES ('Product 1', 10.00),
       ('Product 2', 20.00);